#!/bin/ksh

# Copyright (c) 2016 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

mirror=rsync://mirror.esc7.net/openbsd
mirror=rsync://ftp.eu.openbsd.org/OpenBSD

datadir=$HOME/var/db
allincomp=allobsd.xz
freqincomp=freqobsd.xz
dbname=allobsd.database

cd $datadir || exit 1

if ! [ "$1" = "-B" ]; then
	exec locate -d $datadir/$dbname "$@"
fi

compress() {
	xz -9
}
if ! [ -f $allincomp ]; then
	updateall=1
else
	if [ "$(find $allincomp -mtime +30)" ]; then
		updateall=1
	fi
fi
if [ updateall -eq 1 ]; then
	# update once every 30 days 'everything'
	# XXX once verified it works right, add stripall below
	rsync -rl --exclude='\.\~tmp\~' $mirror/. 2> /dev/null | compress > .$allincomp && \
		mv .$allincomp $allincomp || exit 1
fi

mungeforlocate() {
	awk '
	/\~$/		{next}
	$5 ~ /^\.$/	{next}
	! /^[-d]/	{next}
	/^-/		{t=""}
	/^d/		{t="/"}
			{print $3 "/" $4 "/" $5 t}'
}

# strip freq dirs off 'all' bits
stripall() {
	awk '/ (ftplist|timestamp|Changelogs|OpenSSH\/portable|patches|snapshots)/{next}{print}'
}

# update a few more frequently updated bits every night
for url in $mirror/{ftplist,timestamp,Changelogs,OpenSSH/portable,patches,snapshots}
do
	rsync -rl --exclude='\.\~tmp\~' $url 2> /dev/null
done | compress > .$freqincomp && \
	mv .$freqincomp $freqincomp

{
	xz -d < $allincomp | stripall
	xz -d < $freqincomp
} | sort -u | mungeforlocate | \
	/usr/libexec/locate.mklocatedb > .$dbname && \
	mv .$dbname $dbname
